INSERT INTO NBA.Location(StadiumName, City, [State], ZipCode) VALUES 
('State Farm Arena', 'Atlanta', 'GA', '30303'),
('TD Garden', 'Boston', 'MA', '02114'),
('Rocket Mortgage FieldHouse', 'Cleveland', 'OH', '44115'),
('Smoothie King Center', 'New Orleans', 'LA', '70113'),
('United Center', 'Chicago', 'IL', '60612'),
('American Airlines Center', 'Dallas', 'TX', '75219'),
('Ball Arena', 'Denver', 'CO', '80204'),
('Chase Center', 'San Francisco', 'CA', '94158'),
('Toyota Center', 'Houston', 'TX', '77003'),
('Crypto.com Arena', 'Los Angeles', 'CA', '90015'),
('Crypto.com Arena', 'Los Angeles', 'CA', '90015'),
('FTX Arena', 'Miami', 'FL', '33132'),
('Fiserv Forum', 'Milwaukee', 'WI', '53203'),
('Target Center', 'Minneapolis', 'MN', '55403'),
('Barclays Center', 'Brooklyn', 'NY', '11217'),
('Madison Square Garden','New York', 'NY', '10001'),
('Amway Center', 'Orlando', 'FL', '32801'),
('Gainbridge Fieldhouse', 'Indianapolis', 'IN', '46204'),
('Wells Fargo Center', 'Philadelphia', 'PA', '19148'),
('Footprint Center', 'Phoenix', 'AZ', '85004'),
('Moda Center', 'Portland', 'OR', '97227'),
('Golden 1 Center', 'Sacramento', 'CA', '95814'),
('AT&T Center', 'San Antonio', 'TX', '78219'),
('Paycom Center', 'Oklahoma City', 'OK', '73102'),
('Scotiabank Arena', 'Toronto', 'ON', '11111'),
('Vivint Arena', 'Salt Lake City', 'UT', '84101'),
('FedExForum', 'Memphis', 'TN', '38103'),
('Capital One Arena', 'Washington', 'DC', '20004'),
('Little Caesars Arena', 'Detroit', 'MI', '48201'),
('Spectrum Center', 'Charlotte', 'NC', '28202')